Repository prgrms-aibe-devcourse/aibe3-project1-team02, pull requests merged in 2025-07, with the labels that each got.

#2 [chore] 프로젝트 초기 세팅 및 기본 ui 구조 구성
  next.config.ts
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  src/app/community/[id]/CommunityDetail.tsx
  src/app/community/[id]/page.tsx
  src/app/community/page.tsx
  src/app/destinations/[id]/DestinationDetail.tsx
  src/app/destinations/[id]/page.tsx
  src/app/destinations/page.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/my-plans/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/planner/page.tsx
  src/app/signup/page.tsx
  src/components/Features.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/HeroSection.tsx
  src/components/LoginForm.tsx
  src/components/PopularDestinations.tsx
  src/components/ProductCreate.tsx
  src/components/ProductList.tsx
  src/components/ReviewCreate.tsx
  src/components/ReviewList.tsx
  src/components/SignupForm.tsx
  src/components/TravelPlanning.tsx
  tailwind.config.js
  tsconfig.json
Labels: 💡 feature, ⚙️ chore, 🎨 design, ⚙️ init

#9 [feat] AI 생성 관련 route 구현
  package-lock.json
  package.json
  src/app/api/generate-plan/route.ts
Labels: 💡 feature

#10 [feat] AI에 기반한 여행계획 일정 생성 구현
  src/app/planner/page.tsx
Labels: 💡 feature, 🔧 refactor, 🎨 design

#11 [feat] 로그인 기능 구현 및 헤더 상태변경
  src/components/Header.tsx
  src/components/LoginForm.tsx
Labels: 💡 feature

#14 [feat] AI 추천 기반 여행일정 생성 및 저장 기능 구현
  next.config.ts
  src/app/api/generate-plan/route.ts
  src/app/api/plans/route.ts
  src/app/my-plans/page.tsx
  src/app/planner/page.tsx
Labels: 💡 feature, 🔧 refactor, 🛠️ fix

#17 [feat] 여행 후기 페이지 기능 일부 구현
  package-lock.json
  package.json
  src/app/community/[id]/CommunityDetail.tsx
  src/app/community/[id]/page.tsx
  src/app/community/page.tsx
  src/types/community.ts
Labels: 💡 feature

#30 [FEAT] 여행 후기 조회수기능, 삭제기능, 후기 작성시 이미지 등록시 url에서 파일로 업로드 구현
  src/app/community/[id]/CommunityDetail.tsx
  src/app/community/new/page.tsx
  src/app/community/page.tsx
Labels: 💡 feature

#32 [feat] 내 여행 상세 페이지 수정 기능 구현
  package-lock.json
  package.json
  src/app/api/plans/[id]/route.ts
  src/app/my-plans/[id]/modify/page.tsx
  src/app/my-plans/[id]/page.tsx
Labels: 💡 feature

#40 [feat] 여행지 여행 후기 탭 구현
  src/app/destinations/[id]/DestinationDetail.tsx
Labels: 💡 feature

#44 [fix] 후기 페이지 auth.user 다른 유저의 uuid 받는 버그 수정
  src/app/community/[id]/CommunityDetail.tsx
  src/app/community/new/page.tsx
  src/app/community/page.tsx
Labels: 🛠️ fix

#45 [refactor] 메인페이지 인기여행지 변경 및 라우팅 설정 추가
  public/parisimage.png
  public/tokyoimage.png
  src/components/PopularDestinations.tsx
  src/components/TravelPlanning.tsx
Labels: 🔧 refactor, 🎨 design

#46 [feat] 여행지 패키지 탭 구현
  src/app/destinations/[id]/DestinationDetail.tsx
Labels: 💡 feature

#50 [feat] 대댓글 기능 구현
  src/app/community/[id]/CommunityDetail.tsx
  src/types/community.ts
Labels: 💡 feature

#51 [fix] 내 여행 계획 이미지 미출력 문제 및 상세 페이지 여행지 미출력 문제 해결
  src/app/api/plans/[id]/route.ts
  src/app/api/plans/route.ts
  src/app/my-plans/[id]/modify/page.tsx
  src/app/my-plans/[id]/page.tsx
  src/app/my-plans/page.tsx
Labels: 🛠️ fix

#53 [Feat] 상단바 깜빡임 및 기본이미지 설정
  src/components/Header.tsx
  src/components/SignupForm.tsx
  tailwind.config.js
Labels: 💡 feature, 🎨 design

#54 [feat] 여행지 검색 기능 구현
  src/components/HeroSection.tsx
  src/components/PopularDestinations.tsx
Labels: 💡 feature, 🛠️ fix

#67 [fix] Next.js 동기적 params 에러 해결
  src/app/api/plans/[id]/route.ts
Labels: 🛠️ fix

#71 [Fix] 패키지 탭 예약하기 버그 수정
  src/app/api/plans/route.ts
  src/app/destinations/[id]/DestinationDetail.tsx
  src/app/my-plans/page.tsx
Labels: 🛠️ fix

#72 [feat] 여행 후기 상세 페이지에 이미지 파일 보이게 구현
  src/app/community/[id]/CommunityDetail.tsx
Labels: 💡 feature

#74 [feat] 로그인되지 않았을 때 여행후기 페이지 들어가면 로그인 페이지로 가게 설정
  src/app/community/page.tsx
Labels: 💡 feature

#75 [feat] 내 계획 삭제 기능 및 AI생성 일정 수정 기능 추가
  src/app/api/plans/[id]/route.ts
  src/app/my-plans/[id]/modify/page.tsx
  src/app/my-plans/[id]/page.tsx
  src/components/MyPlanEditor.tsx
Labels: 💡 feature

#76 [feat] 후기 페이지 삭제시 storage에 있는 파일도 삭제
  src/app/community/new/page.tsx
  src/app/community/page.tsx
  src/types/community.ts
Labels: 💡 feature

#80 [Fix] 소셜로그인 관련
  src/app/auth/callback/page.tsx
Labels: 🐛 bug fix

#83 [Fix] 사이트 이름 변경
  package-lock.json
  package.json
  src/components/Features.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/HeroSection.tsx
Labels: 🎨 design

#86 [Design] 메인페이지 애니메이션
  package-lock.json
  package.json
  src/components/HeroSection.tsx
  src/components/PopularDestinations.tsx
Labels: 🎨 design

#88 [fix] 댓글 삭제시 댓글 개수 바로 반영 안되는 이슈
  src/app/community/[id]/CommunityDetail.tsx
Labels: 🐛 bug fix

#90 [design] 여행 후기 댓글 시간 보기 편하게 변경 및 삭제 버튼 왼쪽으로 옮김
  src/app/community/[id]/CommunityDetail.tsx
  src/app/community/page.tsx
  src/components/Header.tsx
Labels: 🎨 design
